### ISSUE TITLE
openseamap.org - no https per default

### ISSUE THREAD

**Issue by stevo01** [OpenSeaMap/general#13]
If the user open openseamap.org in webbrowser, then the websession is running without https.
If the user open https://www.openseamap.orgm then the connection is secured with ssl.

I think the usage of https should be enforced by webserver to:
- avoid that user traffic can be monitored / ensure privacy
- improve google ranking

**Comment by smurfix** [comment]
This makes sense as soon as openseamap.org (and map.openseamap.org) is fixed to not include insecure content. Right now this will cause problems for browsers configured not to allow that.

**Comment by stevo01** [comment]
Hmm, I hope that all needed external services are accessed by https. 
see https://forum.openseamap.org/viewtopic.php?id=2827 for discussion about it ...

**Comment by smurfix** [comment]
What do you mean, you hope? I have checked and they are not.

**Comment by stevo01** [comment]
Thanks for the question. I checked it some month ago and found no link to insecure content or missed the geoserver provided by http://osm.franken.de:8080/geoserver/gwc/service/wms?.

I close the ticket until geoserver is accessable by https. ( we are working on update of this component at the moment )
